filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~